### ISSUE TITLE
Hanging Gz component

### ISSUE THREAD

**Issue by ViktorWalter** [ctu-mrs/mrs_uav_gazebo_testing#3]
![image](https://github.com/ctu-mrs/mrs_uav_gazebo_testing/assets/21334530/6e045530-9ea4-4777-a8a0-e2306da21ae4)
Sometimes, when running two consecutive tests with Gazebo, one instance of Gazebo remains hanging. I suspect this has to do with the chronic Pixhawk driver hanging we've been experiencing for years.
The second test then fails to progress, since the new Gazebo instance never fully loads, making consecutive tests flaky. Notably, the first test exits normally, with `Success`:
![image](https://github.com/ctu-mrs/mrs_uav_gazebo_testing/assets/21334530/3e26de8a-2775-4138-a51c-1e571a824f9b)
I'm experiencing this when running `test/run_tests.sh` in `uvdar_gazebo_plugin`.
Maybe we should add some more "aggressive" killing of prior instances into the testing?

**Comment by klaxalk** [comment]
We actually tackled the issue of exiting PX4 and the related things a few weeks ago when I started to develop the tests. Then, the drone spawner got fixed such that it properly exits PX4 now; otherwise, you would not run a single test.

I do not observe this problem within `mrs_uav_gazebo_simulation`, which now runs 9 consecutive tests... so the problem could be related to
a) you have more than one drone
b) you have a custom plugin that causes this issue.

Could you check what is left running after the tests?

**Comment by ViktorWalter** [comment]
I just ran it. After the test (2nd failed), I have a bunch of mavros nodes running
![image](https://github.com/ctu-mrs/mrs_uav_gazebo_testing/assets/21334530/4f768f79-0d67-4577-a6b2-092a5e665a92)
The failure was different now, however - the message in the OP didn't appear, but the test rather resulted in absurd measurements, as if the pose of one of the drones was somehow out of scope.
![image](https://github.com/ctu-mrs/mrs_uav_gazebo_testing/assets/21334530/7b5c087c-f0f0-4747-98e2-c6fcb529b513)
For context, this means that the camera somehow outputted a UV point at [0:0], which implies the relative pose of the target was borked.
After killing the nodes manually, the tests run fine for now - it is difficult to intentionally replicate.
Neither of the log files in the screenshots exists - the directories contain other log files, but not the mavros ones.

**Comment by klaxalk** [comment]
Hmm, are you running the tests in series? That is the `-p 1` in my shell scripts. Without it, that might cause the exact issue. Although separate ROS cores isolate the individual tests, the tests will interfere because of the fixed ports that bind Gazebo with Mavros.

**Comment by klaxalk** [comment]
The same applies for running the tests alongside a normal simulation session...

**Comment by ViktorWalter** [comment]
![image](https://github.com/ctu-mrs/mrs_uav_gazebo_testing/assets/21334530/541fe9cd-73bc-4e41-ab5e-4f8ee4784d37)
This is the content of the script which I was running the tests with.
The `-p 1` flag is there.
The tests were evidently running one after the other.

**Comment by klaxalk** [comment]
Could you please try to restart your PC? Typically when the things go south like this with rogue processes, it won't fix itself. And the original cause might even be something unrelated...

**Comment by ViktorWalter** [comment]
![image](https://github.com/ctu-mrs/mrs_uav_gazebo_testing/assets/21334530/483951b3-147d-4392-9fa1-072e36e71ec6)
I guess it deserved some rest...

**Comment by klaxalk** [comment]
I have run your tests several times around and nothing is left hanging on my PC. So I suspect it might be a singular problem with your instance of the OS. Try restarting pls :-).

**Comment by ViktorWalter** [comment]
After a restart, consecutive runs of the test don't fail. But given the spurious nature of these issues I don't know how significant it is.

**Comment by klaxalk** [comment]
It is not very significant. The tests run on a fresh Ubuntu machine on Github every time. So I would wait till we see the problem there. In the meantime, consider it low priority.
